[versions]
kotlin = "1.9.10"
android_gradle_plugin = "8.1.4"
compose = "1.5.11"

android_sdk_compile = "34"
android_sdk_target = "34"
android_sdk_min = "26"

sqldelight = "2.0.0"
ktor = "2.3.6"
napier = "2.6.1"
kotlinx_coroutines = "1.7.3"
kotlinx_date_time = "0.4.1"
kotlinx_immutable_collections = "0.3.6"
decompose = "2.1.4-compose-experimental"
essenty = "1.2.0"
androidx_activity = "1.8.1"
androidx_appcompat = "1.6.1"
androidx_core = "1.12.0"
androidx_collection = "1.3.0"
androidx_test_runner = "1.5.2"
androidx_test_rules = "1.5.0"
androidx_work = "2.8.1"
androidx_datastore = "1.1.0-alpha06"
androidx_browser = "1.7.0"
coil = "2.5.0"
spotless = "6.22.0"
ktfmt = "0.44"
kotlininject = "0.6.3"
ksp = "1.9.10-1.0.13"
material_color_utilities = "1.0.0-alpha01"
ksoup = "0.2.1"
sentry = "0.3.0"
sentry_android = "3.14.0"
buildKonfig = "0.14.0"
sqliteAndroid = "3.43.0"
windowSizeClass = "0.3.1"
desugarJdk = "2.0.4"
lyricist = "1.6.2"
atomicfu = "0.23.1"
okio = "3.6.0"
paging = "3.3.0-alpha02-0.4.0"
stately = "2.0.5"
xmlutil = "0.86.2"

[libraries]
compose_runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose_foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose_ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose_ui_util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "compose" }
compose_material = { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
compose_material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
compose_resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
ktor_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_client_okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_client_darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor_client_logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlin_test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines" }
kotlinx_coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx_coroutines" }
kotlinx_datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx_date_time" }
kotlinx_immutable_collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx_immutable_collections" }
kotlinx_atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
sqldelight_driver_android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight_driver_native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight_extensions_coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight_extensions_paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqldelight" }
sqldelight_sqlite_dialect = { module = "app.cash.sqldelight:sqlite-3-24-dialect", version.ref = "sqldelight" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose_extensions_compose = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
essenty_lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
essenty_backhandler = { module = "com.arkivanov.essenty:back-handler", version.ref = "essenty" }
androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx_appcompat" }
androidx_core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_collection = { module = "androidx.collection:collection", version.ref = "androidx_collection" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx_test_runner" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx_test_rules" }
androidx_work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx_work" }
androidx_datastore_okio = { module = "androidx.datastore:datastore-core-okio", version.ref = "androidx_datastore" }
androidx_datastore_preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx_datastore" }
androidx_browser = { module = "androidx.browser:browser", version.ref = "androidx_browser" }
coil_compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
kotlininject-compiler = { module = 'me.tatarka.inject:kotlin-inject-compiler-ksp', version.ref = 'kotlininject' }
kotlininject-runtime = { module = 'me.tatarka.inject:kotlin-inject-runtime', version.ref = 'kotlininject' }
material_color_utilities = { module = "dev.sasikanth:material-color-utilities", version.ref = "material_color_utilities" }
ksoup = { module = "com.mohamedrejeb.ksoup:ksoup-html", version.ref = "ksoup" }
sentry = { module = "io.sentry:sentry-kotlin-multiplatform", version.ref = "sentry" }
sqliteAndroid = { module = "com.github.requery:sqlite-android", version.ref = "sqliteAndroid" }
windowSizeClass = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "windowSizeClass" }
desugarJdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }
lyricist = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }
lyricist-processor = { module = "cafe.adriel.lyricist:lyricist-processor", version.ref = "lyricist" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "paging" }
stately-isolate = { module = "co.touchlab:stately-isolate", version.ref = "stately" }
stately-iso-collections = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }

[plugins]
android_application = { id = "com.android.application", version.ref = "android_gradle_plugin" }
android_library = { id = "com.android.library", version.ref = "android_gradle_plugin" }
kotlin_multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin_parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ksp = { id = 'com.google.devtools.ksp', version.ref = 'ksp' }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
sentry_android = { id = "io.sentry.android.gradle", version.ref = "sentry_android" }

[bundles]
compose = [ "compose_runtime", "compose_foundation", "compose_material", "compose_material3", "compose_resources", "compose_ui", "compose_ui_util" ]
kotlinx = [ "kotlinx_coroutines", "kotlinx_datetime", "kotlinx_immutable_collections" ]
androidx_test = [ "androidx_test_runner", "androidx_test_rules" ]
xmlutil = [ "xmlutil-core", "xmlutil-serialization" ]
